// Dependencies with "use client" files that plugin-rsc would leave external.
//
// plugin-rsc bundles a dependency into the server graphs - and so sees its
// directives - only when the dependency declares react as a peer. That is
// the right signal for a library written for React. It misses the package
// that imports react and never says so: a component wrapper generated by a
// tool, a workspace package with react under dependencies, a published
// package whose author forgot. Left external, its "use client" is a string
// nobody reads, the rsc environment loads it under the react-server
// condition, and the first useState inside it fails at render with an error
// that names React and not the package.
//
// So the direct dependencies are read once at config time: any that plugin-rsc
// would not bundle, and that carries a "use client" directive in one of its
// files, is bundled here. Direct dependencies only - a directive two levels
// down is the concern of the package between, which declared it.

import { existsSync, readdirSync, readFileSync, realpathSync, statSync, openSync, readSync, closeSync } from "node:fs";
import { dirname, join } from "node:path";

/** A directive at the top of a file: comments may precede it, code may not. */
const DIRECTIVE = /^(?:\s|\/\/[^\n]*\n|\/\*[\s\S]*?\*\/)*(?:'use client'|"use client")\s*;?/;

const SOURCE = /\.(?:m?js|cjs|jsx)$/;

/** The most files read per package before giving up: a bound, not a budget. */
const FILE_CAP = 3000;

/** Enough of a file to hold a licence header and the directive after it. */
const HEAD_BYTES = 2048;

/** The packages plugin-rsc handles itself, and this one. */
const OWN = new Set(["react", "react-dom", "react-server-dom-webpack", "@vitejs/plugin-rsc"]);

interface PackageJson {
  name?: string;
  dependencies?: Record<string, string>;
  peerDependencies?: Record<string, string>;
}

function readJson(path: string): PackageJson | null {
  try {
    return JSON.parse(readFileSync(path, "utf8")) as PackageJson;
  } catch {
    return null;
  }
}

/** Where `name` is installed, walking up from `from` the way resolution does. */
export function packageDir(name: string, from: string): string | null {
  let dir = from;

  for (;;) {
    const candidate = join(dir, "node_modules", name);

    if (existsSync(join(candidate, "package.json"))) return candidate;

    const parent = dirname(dir);

    if (parent === dir) return null;

    dir = parent;
  }
}

function realpathOf(path: string): string {
  try {
    return realpathSync(path);
  } catch {
    return path;
  }
}

function headOf(path: string): string {
  const fd = openSync(path, "r");

  try {
    const buffer = Buffer.alloc(HEAD_BYTES);
    const read = readSync(fd, buffer, 0, HEAD_BYTES, 0);

    return buffer.toString("utf8", 0, read);
  } finally {
    closeSync(fd);
  }
}

/** Whether any source file under `dir` opens with "use client". */
export function hasClientDirective(dir: string): boolean {
  return someSourceFile(dir, (path) => DIRECTIVE.test(headOf(path)));
}

/** An import of react-dom's server renderer, static or dynamic, ESM or CJS. */
const SERVER_RENDERER_IMPORT = /["']react-dom\/server(?:\.[a-z]+)?["']/;

/** The largest file worth reading whole for an import: a bundled dist, not a data table. */
const WHOLE_FILE_CAP = 512 * 1024;

/**
 * Whether any source file under `dir` imports react-dom/server.
 *
 * For a dependency left external where server components render: its
 * imports are never resolved by the build, so the renderer stub that names
 * the app file for a direct import never sees this one. @react-email/render
 * is the usual case - an action imports it, the build says nothing, and the
 * first call throws React's refusal at a visitor.
 */
export function importsServerRenderer(dir: string): boolean {
  return someSourceFile(dir, (path) => {
    try {
      if (statSync(path).size > WHOLE_FILE_CAP) return false;

      return SERVER_RENDERER_IMPORT.test(readFileSync(path, "utf8"));
    } catch {
      return false;
    }
  });
}

/** Whether `test` holds for some source file under `dir`, within the cap. */
function someSourceFile(dir: string, test: (path: string) => boolean): boolean {
  const pending = [dir];
  let seen = 0;

  while (pending.length) {
    const current = pending.pop()!;
    let entries: string[];

    try {
      entries = readdirSync(current);
    } catch {
      continue;
    }

    for (const entry of entries) {
      if (entry === "node_modules" || entry.startsWith(".")) continue;

      const path = join(current, entry);
      let stat;

      try {
        stat = statSync(path);
      } catch {
        continue;
      }

      if (stat.isDirectory()) {
        pending.push(path);
        continue;
      }

      if (!SOURCE.test(entry)) continue;
      if (++seen > FILE_CAP) return false;

      try {
        if (test(path)) return true;
      } catch {
        // Unreadable is neither.
      }
    }
  }

  return false;
}

/** Whether a package says it uses React, as a peer or as a dependency. */
function usesReact(manifest: PackageJson | null): boolean {
  return !!manifest && ("react" in (manifest.peerDependencies ?? {}) || "react" in (manifest.dependencies ?? {}));
}

/**
 * The dependencies of a bundled package that use React, and theirs.
 *
 * Bundling the package that carries the directive is not enough: the
 * runtime it calls into - @stencil/react-output-target under a generated
 * wrapper - is its own package, with react as a peer, and plugin-rsc's
 * crawl never reached it because it only descends through packages that
 * declared React. Left external, that runtime loads React through Node
 * while everything else gets it through Vite: two copies, and the hooks
 * dispatcher is null in one of them. Every React-using dependency under
 * a bundled package is bundled with it.
 */
function reactDependenciesOf(dir: string, into: Set<string>, seen: Set<string>): void {
  const manifest = readJson(join(dir, "package.json"));

  for (const name of Object.keys(manifest?.dependencies ?? {})) {
    if (OWN.has(name) || seen.has(name)) continue;

    seen.add(name);

    // From where the package really is: under Bun's store a symlink in the
    // app's node_modules points into .bun/<pkg>@<v>/node_modules/<pkg>, and
    // the dependency sits beside it there, not beside the symlink.
    const depDir = packageDir(name, realpathOf(dir));

    if (!depDir || !usesReact(readJson(join(depDir, "package.json")))) continue;

    into.add(name);
    reactDependenciesOf(depDir, into, seen);
  }
}

/**
 * The direct dependencies of the project at `root` that plugin-rsc would
 * leave external and that carry a "use client" file - and the React-using
 * dependencies under each, which have to be bundled with it.
 */
export function clientPackages(root: string): string[] {
  const own = readJson(join(root, "package.json"));

  if (!own?.dependencies) return [];

  const found = new Set<string>();

  for (const name of Object.keys(own.dependencies)) {
    if (OWN.has(name) || name.startsWith("@rsc-kit/")) continue;

    const dir = packageDir(name, root);

    if (!dir) continue;

    const manifest = readJson(join(dir, "package.json"));

    // plugin-rsc's own rule: react as a peer, and the package is bundled already.
    if (manifest?.peerDependencies && "react" in manifest.peerDependencies) continue;

    if (!hasClientDirective(dir)) continue;

    found.add(name);
    reactDependenciesOf(dir, found, new Set([name]));
  }

  return [...found].sort();
}
