// Compiling an app to a single Bun binary.
//
// `bun build --compile` follows imports and nothing else, so a host that reads
// its assets from a directory compiles to an executable that answers every
// route and 404s every stylesheet — served, unstyled, never hydrating, with
// nothing on the server side to say so.
//
// So this owns the whole step rather than asking an app to arrange it:
// generate the module that imports the assets, generate the entry that serves
// them, and run the compile. The app writes none of that, which matters
// because an entry importing embedded files is Bun-only — a shared one would
// break every Node and Workers deployment the same package supports.
//
//     import { compile } from '@rsc-router/core/compile'
//
//     await compile({
//       engine: './build/dist/rsc/index.js',
//       assets: './build/public/assets',
//       prerendered: './build/static',
//       outfile: './app',
//     })

import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import { writeEmbedModule } from './embed.js'

export interface CompileOptions {
  /** The built engine bundle the worker loads. */
  engine: string
  /** The browser build. */
  assets: string
  /** What the prerenderer wrote, if it ran. */
  prerendered?: string
  /** Where to put the binary. */
  outfile: string
  /** Staging for the generated entry and asset module. */
  workDir?: string
  /** The url prefix assets are served under. */
  assetsPrefix?: string
  /** Default port, when PORT is unset. */
  port?: number
  /**
   * Strip names and whitespace. On by default.
   *
   * The server bundle is not read by anyone, so the only reason to turn it off
   * is a stack trace you are trying to follow — and `sourcemap` covers that
   * without giving up the size.
   */
  minify?: boolean
  /**
   * Compile to bytecode ahead of time. On by default.
   *
   * Bun's claim is faster start-up; measured here it was 45ms against 48ms,
   * which is inside the noise of this machine — so treat it as free rather
   * than as a win. Its one real constraint is already met: the entry this
   * generates has no top-level await, which bytecode refuses.
   */
  bytecode?: boolean
  /** 'linked' by default, so a stack trace in production points somewhere. */
  sourcemap?: 'none' | 'linked' | 'inline' | 'external'
  /**
   * Build for another platform — `bun-linux-x64`, `bun-linux-arm64`,
   * `bun-windows-x64`, `bun-darwin-arm64`.
   *
   * Bun downloads that platform's runtime the first time, so the first
   * cross-compile is slow and later ones are not. Building a Linux binary from
   * a Mac is the ordinary case for a deploy.
   */
  target?: string
  /**
   * Anything else Bun.build takes, merged last.
   *
   * `compile` is merged key by key rather than replaced, so passing
   * `{ compile: { windows: { hideConsole: true } } }` cannot accidentally drop
   * the outfile — which is silently ignored if it moves to the top level.
   */
  bun?: Record<string, unknown>
}

/**
 * The entry, generated rather than written by the app.
 *
 * Assets become Bun.serve static routes, built once at boot: that is where the
 * ETag, the 304 on a matching If-None-Match, and the route matching come from,
 * none of which a per-request handler gets for free.
 *
 * No top-level await anywhere in it — an async IIFE instead — because
 * `--bytecode` refuses a module that has one, and bytecode is most of the
 * start-up win.
 */
function entrySource(engineSpecifier: string, embedSpecifier: string, port: number): string {
  return `// GENERATED by @rsc-router/core/compile — do not edit.
import { createRscHandler } from '@rsc-router/core/host'
import * as engine from ${JSON.stringify(engineSpecifier)}
import { assetPaths, pagePaths, TYPES } from ${JSON.stringify(embedSpecifier)}

;(async () => {
  const rsc = createRscHandler({
    engine,
    // Reads what the binary carries. A miss falls through to rendering, the
    // same as a partial prerender on disk.
    prerendered: async (name) => {
      const path = pagePaths[name]

      return path ? await Bun.file(path).text() : null
    },
  })

  // Built once, not per request. Aliases pointing at the same file share one
  // Response so the bytes are held once.
  const byPath = new Map()
  const routes = {}

  await Promise.all(
    Object.entries(assetPaths).map(async ([url, path]) => {
      let pending = byPath.get(path)

      if (!pending) {
        const file = Bun.file(path)

        pending = file.bytes().then(
          (bytes) =>
            new Response(bytes, {
              headers: {
                'Content-Type': TYPES[url.split('.').pop() ?? ''] ?? file.type ?? 'application/octet-stream',
                // Content-hashed by the build, so this is safe.
                'Cache-Control': 'public, max-age=31536000, immutable',
              },
            }),
        )

        byPath.set(path, pending)
      }

      routes[url] = await pending
    }),
  )

  const server = Bun.serve({
    port: Number(Bun.env.PORT ?? ${port}),
    routes,
    fetch: async (request) => (await rsc(request)) ?? new Response('Not found', { status: 404 }),
  })

  console.log(\`listening on http://localhost:\${server.port}\`)
})()
`
}

/** Build the binary. Returns where it was written. */
export async function compile(options: CompileOptions): Promise<string> {
  if (typeof Bun === 'undefined') {
    throw new Error('compile() needs the Bun runtime — run it with `bun run`.')
  }

  const work = resolve(options.workDir ?? '.rsc-compile')
  const embedFile = resolve(work, 'embedded.ts')
  const entryFile = resolve(work, 'entry.ts')
  const outfile = resolve(options.outfile)

  mkdirSync(work, { recursive: true })

  const found = writeEmbedModule({
    assets: options.assets,
    prerendered: options.prerendered,
    out: embedFile,
    prefix: options.assetsPrefix ?? '/assets/',
  })

  const specifier = (abs: string) => {
    const rel = relative(work, resolve(abs)).replace(/\\/g, '/')

    return rel.startsWith('.') ? rel : './' + rel
  }

  writeFileSync(
    entryFile,
    entrySource(specifier(options.engine), './embedded.ts', options.port ?? 3000),
  )

  mkdirSync(dirname(outfile), { recursive: true })

  const { compile: overrides, ...rest } = options.bun ?? {}

  const result = await Bun.build({
    entrypoints: [entryFile],
    minify: options.minify ?? true,
    sourcemap: options.sourcemap ?? 'linked',
    bytecode: options.bytecode ?? true,
    // Read at runtime by React to pick its build. Left unset, a production
    // client is served a development payload: hydration fails, the page
    // renders perfectly, and nothing is interactive or logged.
    define: { 'process.env.NODE_ENV': JSON.stringify('production') },
    ...rest,
    // outfile has to live in here: a top-level one is ignored for a standalone
    // build, and the binary lands somewhere else entirely.
    compile: {
      outfile,
      ...(options.target ? { target: options.target } : {}),
      ...(typeof overrides === 'object' ? overrides : {}),
    },
  } as Parameters<typeof Bun.build>[0])

  if (!result.success) {
    throw new Error(
      `Could not compile:\n${result.logs.map((l) => String(l)).join('\n')}`,
    )
  }

  console.log(
    `compiled ${outfile} — ${found.assets} assets and ${found.prerendered} stored pages inside it`,
  )

  return outfile
}
